### DISCUSSION TITLE
[Prio low / tbd] paperless-ai uses same port as Gotenberg

### DISCUSSION THREAD

**Discussion by thorschtn** [clusterzx/paperless-ai#137] [Ideas implemented]
Gotenberg (https://github.com/gotenberg/gotenberg) is often used in paperlessNGX setups to import other file formats than PDF (XLSX, DOCX, HTML, ...).

By default, Gotenberg uses the same port (3000) as paperless-ai.

I know that changing the port shouldn't be a problem for the user, but inexperienced users could be overwhelmed by it.

Maybe we want to change the default port for paperless-ai?

**Comment by clusterzx** [comment]
I rethink about this issue right now. Normally there wont be a problem, as you can set the exposed port yourself. 

As paperless-ai runs in its own virtual network in docker there wont be a conflict internally, externally you can define it by just changing it?

**Comment by thorschtn** [comment]
As I said, no issue for me, but not sure how it turns out, when unexperienced Users show up.

**Reply by mamema** [reply]
just thinking about that. As the exposed port can be changed, externally not a problem, but if i already have a docker container running, which uses port 3000 internally, does this work? I guess not. Other docker solutions are solving this with an env var where the internal port can be changed....

**Reply by paradizelost** [reply]
The only way this is an issue is if the container is in host networking mode. when you define your containers, you specify what external port maps to what internal port. This is therefor adjustable by the end-user at runtime.

**Comment by nowell-morris** [comment]
I agree that the 3000 ought to default to something else.  I came here specifically to see if anyone else had run into it.  I'll be setting paperless-ai up next to my existing paperless-ngx installation, and so I will need to change the port.  I've been excited to see this project grow from when it was shared on Reddit.  I think it is still very early in the project and a switch from 3000 is advisable for going forward.  Maybe 3300? 3030? 2999?

**Reply by clusterzx** [reply]
I really appreciate that you watched the journey so far 😊
Port 3000 was used as this is the most used port in nodejs projects. 
It's like the developer port of almost every javascript framework. 

But I agree that in some cases it could interfere with other services when running in host network mode. 

But running it on bridge mode in its own network adapter it won't interfere with anything. The expose port you can define for your self already.

**Reply by paradizelost** [reply]
I have both paperless-ai and paperless-ngx with tika and gotenberg side by side on the same machine without issue as well without any kind of conflict.

**Reply by mrepetto94** [reply]
I think the problem is impacting also people like myself using podman and the podman's pod. An environmental variable setting the internal port at start will be optimal in my usecase.

**Reply by clusterzx** [reply]
You can define the port via the docker env now.

**Reply by mrepetto94** [reply]
Cool! How? I did not see it in the wiki, my bad.

**Reply by clusterzx** [reply]
docker-compose.yml there you can set it or see the var. 

Had not updated the wiki as I thought it would be self explanatory, but I think it is not in the end after all 😬

**Reply by mrepetto94** [reply]
It is indeed, but not for people using podman :-D

**Reply by clusterzx** [reply]
Ok, but what does Podman need? I dont have or use podman. So I do not support it :D

**Reply by mrepetto94** [reply]
In a podman's pod, rerouting the ports is impossible as you would do in docker-compose. All services share the same virtual host and the reroute of ports is done only outside the pod. But with the env variable, everything works fine. I'll attach an Ansible notebook to give you an idea of what the pod and its port routing look like.

```yml
- name: Setup Paperless NGX Pod
  hosts: localhost
  vars:
    pod_name: paperless_ngx
    common_quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Service]
        Restart=always
        RestartSec=60
      - |
        [Install]
        WantedBy=default.target

  tasks:

    - name: Create Paperless NGX Pod
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        ports:
          - 8000:8000
          - 3003:3003
        recreate: true
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target

    - name: Run Redis Container (Broker)
      containers.podman.podman_container:
        name: redis
        image: docker.io/library/redis:7
        state: quadlet
        pod: "{{ pod_name }}.pod"
        quadlet_options: "{{ common_quadlet_options }}"

    - name: Run PostgreSQL Container (DB)
      containers.podman.podman_container:
        name: postgres
        image: docker.io/library/postgres:16
        state: quadlet
        pod: "{{ pod_name }}.pod"
        quadlet_options: "{{ common_quadlet_options }}"

    - name: Run Paperless NGX Container (Webserver)
      containers.podman.podman_container:
        name: paperless-ngx
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        state: quadlet
        pod: "{{ pod_name }}.pod"
        env:
          PAPERLESS_REDIS: redis://redis:6379
          PAPERLESS_DBHOST: postgres
          PAPERLESS_TIKA_ENABLED: 1
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://tika:9998
        quadlet_options: "{{ common_quadlet_options }}"

    - name: Run Gotenberg Container
      containers.podman.podman_container:
        name: gotenberg
        image: docker.io/gotenberg/gotenberg:8.7
        state: quadlet
        pod: "{{ pod_name }}.pod"
        command:
          - "gotenberg"
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
        quadlet_options: "{{ common_quadlet_options }}"

    - name: Run Apache Tika Container
      containers.podman.podman_container:
        name: tika
        image: docker.io/apache/tika:latest
        state: quadlet
        pod: "{{ pod_name }}.pod"
        quadlet_options: "{{ common_quadlet_options }}"

    - name: Run Paperless AI
      containers.podman.podman_container:
        name: paperless-ai
        image: docker.io/clusterzx/paperless-ai:latest
        state: quadlet
        pod: "{{ pod_name }}.pod"
        env:
          PAPERLESS_AI_PORT: 3003

    - name: Reload systemd to recognize new services
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user

    - name: Start Paperless NGX and its services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        scope: user
        enabled: true
      loop:
        - "{{ pod_name }}-pod"
        - redis
        - postgres
        - paperless-ngx
        - gotenberg
        - tika
        - paperless-ai

```
