### DISCUSSION TITLE
Error during initial document scan when connecting to existing Paperless-NGX installation

### DISCUSSION THREAD

**Discussion by SalmoLabViserion** [clusterzx/paperless-ai#420] [Q&A]
I'm running since years a Paperless-NGX installation on my Synology NAS. Currently there are 5388 documents and 73 tags. 

Installation of Paperless-AI went smoothly, but it fails during the initial document scan with the following errors:

```
[ERROR] refreshing tag cache: Cannot read properties of undefined (reading 'forEach')
[ERROR] during initial document scan: TypeError: Cannot read properties of undefined (reading 'forEach')
```

Note: The Paperless-AI installation and setup works in principle. When I connect Paperless-AI to a fresh Paperless-NGX installation, Paperless-AI scans and analyzes the documents as expected.

**Comment by SalmoLabViserion** [comment]
So, this error also happens after some point with a fresh Paperless-NGX installation? 

```
[ERROR] refreshing tag cache: Cannot read properties of undefined (reading 'forEach')
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read properties of undefined (reading 'forEach')
    at PaperlessService.refreshTagCache (/app/services/paperlessService.js:69:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PaperlessService.ensureTagCache (/app/services/paperlessService.js:57:7)
    at async PaperlessService.getAllDocuments (/app/services/paperlessService.js:531:7)
    at async /app/routes/setup.js:2163:24
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'forEach')
      at PaperlessService.refreshTagCache (/app/services/paperlessService.js:69:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async PaperlessService.ensureTagCache (/app/services/paperlessService.js:57:7)
      at async PaperlessService.getAllDocuments (/app/services/paperlessService.js:531:7)
      at async /app/routes/setup.js:2163:24
} reason: TypeError: Cannot read properties of undefined (reading 'forEach')
    at PaperlessService.refreshTagCache (/app/services/paperlessService.js:69:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PaperlessService.ensureTagCache (/app/services/paperlessService.js:57:7)
    at async PaperlessService.getAllDocuments (/app/services/paperlessService.js:531:7)
    at async /app/routes/setup.js:2163:24
```

**Reply by clusterzx** [reply]
Can you show me your .env file? Of course you can redact the sensitive information like api keys. But the urls would be good to have in clear form.

**Reply by SalmoLabViserion** [reply]
Thanks for your reply! I've tried several scenarios now with fresh installations of both Paperless-NGX and Paperless-AI. Independent on the Paperless-AI settings (e.g. use existing tags/correspondents = yes/no), Paperless-AI  fails to modify any new documents after processing/scanning about 16 documents with the following error:

```
[ERROR] refreshing tag cache: Cannot read properties of undefined (reading 'forEach')
[ERROR] in processTags: TypeError: Cannot read properties of undefined (reading 'forEach')
[ERROR] processing document 54: Error: [ERROR] Failed to process tags: Cannot read properties of undefined (reading 'forEach')

```

Interestingly, the document scanning / AI analysis still works (also in "manual" mode), but fails to update the document with the generated tags.

Here's part of the logs:

```
TEST 2:  ai-processed
[DEBUG] Refreshing tag cache...
[DEBUG] Document 88 rights for AI User - processed
Validating Paperless config for: https://paperlessngx.dragonstone.synology.me/api/documents/
[DEBUG] Thumbnail already cached
[ERROR] refreshing tag cache: Cannot read properties of undefined (reading 'forEach')
[ERROR] in processTags: TypeError: Cannot read properties of undefined (reading 'forEach')
    at PaperlessService.refreshTagCache (/app/services/paperlessService.js:69:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PaperlessService.ensureTagCache (/app/services/paperlessService.js:57:7)
    at async PaperlessService.processTags (/app/services/paperlessService.js:249:7)
    at async buildUpdateData (/app/server.js:226:32)
    at async scanInitial (/app/server.js:368:28)
    at async startScanning (/app/server.js:539:7)
[ERROR] processing document 54: Error: [ERROR] Failed to process tags: Cannot read properties of undefined (reading 'forEach')
    at PaperlessService.processTags (/app/services/paperlessService.js:333:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async buildUpdateData (/app/server.js:226:32)
    at async scanInitial (/app/server.js:368:28)
    at async startScanning (/app/server.js:539:7)
[DEBUG] Document 55 rights for AI User - processed
AI provider: custom
Custom AI config: {
  baseURL: 'https://generativelanguage.googleapis.com/v1beta/openai',
  apiKey: 'xxxx',
  model: 'gemini-2.0-flash'
}
[DEBUG] [13.03.25, 16:05] OpenAI request sent
[DEBUG] [13.03.25, 16:05] Total tokens: 929
Repsonse from AI service: {
  document: {
    title: 'Prüfungsergebnisse',
    correspondent: 'ALTE',
    tags: [ 'Prüfung', 'Sprachzertifikat' ],
    document_type: 'Zertifikat',
    document_date: '2024-01-05',
    language: 'de'
  },
  metrics: { promptTokens: 840, completionTokens: 89, totalTokens: 929 },
  truncated: false
}
```

**Reply by SalmoLabViserion** [reply]
Here are the Paperless-AI install setting:

```
services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperlessngx-ai
    network_mode: bridge
    volumes:
      - /volume1/docker/paperlessngx-ai:/app/data
    ports:
      - "3747:3000"
    restart: unless-stopped

volumes:
    paperlessngx-ai:
```

**Reply by SalmoLabViserion** [reply]
And here are the contents of the .env file of my Paperless-NGX installation:

```
services:
  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: PaperlessNGX-REDIS
    hostname: paper-redis
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1030:65537
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/paperlessngx/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: on-failure:5

  db:
    image: postgres:17
    container_name: PaperlessNGX-DB
    hostname: paper-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperlessuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/paperlessngx/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxxx
    restart: on-failure:5

  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: PaperlessNGX-GOTENBERG
    hostname: gotenberg
    security_opt:
      - no-new-privileges:true
    user: 1030:65537
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: on-failure:5

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: PaperlessNGX-TIKA
    hostname: tika
    security_opt:
      - no-new-privileges:true
    user: 1030:65537
    restart: on-failure:5

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX
    hostname: paperless-ngx
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8777:8000
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume:rw
      - /volume1/docker/paperlessngx/trash:/usr/src/paperless/trash:rw
    environment:
      PAPERLESS_REDIS: redis://:redispass@paper-redis:6379
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: paper-db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperlessuser
      PAPERLESS_DBPASS: paperlesspass
      PAPERLESS_EMPTY_TRASH_DIR: ../trash
      PAPERLESS_FILENAME_FORMAT: '{{ created_year }}/{{ correspondent }}/{{ document_type }}/{{ title }}'
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 6
      PAPERLESS_TASK_WORKERS: 1
      USERMAP_UID: 1030
      USERMAP_GID: 65537
      PAPERLESS_TIME_ZONE: Europe/Bucharest
      PAPERLESS_ADMIN_USER: xxx
      PAPERLESS_ADMIN_PASSWORD: xxx
      PAPERLESS_URL: https://paperlessngx.xxx.synology.me
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperlessngx.xxx.synology.me
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      tika:
        condition: service_started
      gotenberg:
        condition: service_started
```

Thanks a lot for your help!
