### ISSUE TITLE
Documents being processed even though they don't have a tag (2.2.1)

### ISSUE THREAD

**Issue by tvories** [clusterzx/paperless-ai#167]
**Describe the bug**

I have set the field "Process only specific pre tagged documents?" to "yes" but documents that don't have the tag that I specified (`ai-assisted`) are still being processed.

I would assume that any document that doesn't have a tag of `ai-assisted` would not be processed based on the wording.

Screenshot of settings:

![Image](https://github.com/user-attachments/assets/686f29ab-d4a2-4214-9cd6-28ec3c260eb8)

ENV settings for my deployment (running in kubernetes)

```yaml
PAPERLESS_API_URL: https://paperless.${SECRET_DOMAIN}/api
              AI_PROVIDER: ollama
              SCAN_INTERVAL: "*/30 * * * *"
              SYSTEM_PROMPT: |
                You are a personalized document analyzer. Your task is to analyze documents and extract relevant information.\n\nAnalyze the document content and extract the following information into a structured JSON object:\n\n1. title: Create a concise, meaningful title for the document\n2. correspondent: Identify the sender/institution but do not include addresses\n3. tags: Select up to 4 relevant thematic tags\n4. document_date: Extract the document date (format: YYYY-MM-DD)\n5. language: Determine the document language (e.g. "de" or "en")\n      \nImportant rules for the analysis:\n\nFor tags:\n- FIRST check the existing tags before suggesting new ones\n- Use only relevant categories\n- Maximum 4 tags per document, less if sufficient (at least 1)\n- Avoid generic or too specific tags\n- Use only the most important information for tag creation\n- The output language is the one used in the document! IMPORTANT!\n\nFor the title:\n- Short and concise, NO ADDRESSES\n- Contains the most important identification features\n- For invoices/orders, mention invoice/order number if available\n- The output language is the one used in the document! IMPORTANT!\n\nFor the correspondent:\n- Identify the sender or institution\n\nFor the document date:\n- Extract the date of the document\n- Use the format YYYY-MM-DD\n- If multiple dates are present, use the most relevant one\n\nFor the language:\n- Determine the document language\n- Use language codes like "de" for German or "en" for English\n- If the language is not clear, use "und" as a placeholder

                Return the result EXCLUSIVELY as a JSON object. The Tags and Title MUST be in the language that is used in the document.:

                {
                  "title": "xxxxx",
                  "correspondent": "xxxxxxxx",
                  "tags": ["Tag1", "Tag2", "Tag3", "Tag4"],
                  "document_date": "YYYY-MM-DD",
                  "language": "en/de/es/..."
                }
              PROCESS_PREDEFINED_DOCUMENTS: yes
              TAGS: ai-assisted
              ADD_AI_PROCESSED_TAG: yes
              AI_PROCESSED_TAG_NAME: ai-processed
              USE_PROMPT_TAGS: no
```

**To Reproduce**
1. Deploy paperless-ai and hook it up to paperless-ngx
2. Use environment variables to bring up the docker container (my environment is in kubernetes, but the env variables should act the same)
3. Set the environment variable `PROCESS_PREDEFINED_DOCUMENTS` to `yes`
4. Also set the setting "Process only specific pre-tagged documents?" to "yes" and provide a tag of `ai-assisted` as the tag for that field
5. Save settings and restart the app
6. Watch paperless-ai process docs that do not have the `ai-assisted` tag on them

**Expected behavior**
I should see only 50 of 2200+ documents being modified. Instead, it appears paperless-ai is processing all documents in my paperless-ngx instance

**How is this being deployed?:**
 - OS: Talos Linux for kubernetes v1.8.4
 - paperless-version: 2.2.0

**Browser:**
Firefox 134.0

I could be misunderstanding the purpose of the `PROCESS_PREDEFINED_DOCUMENTS` env variable OR the "Process only specific pre-tagged documents?" field, but my assumption is that there should be a way to process only specifically tagged documents.

**Additional Screenshots**

![Image](https://github.com/user-attachments/assets/2652877d-4ff0-4249-aa04-cd097e62d85c)

![Image](https://github.com/user-attachments/assets/f5780378-c9d1-463f-82cd-3506c630791a)
