### ISSUE TITLE
Setup appearing after each container recreation

### ISSUE THREAD

**Issue by Kosmoshn** [clusterzx/paperless-ai#220]
**Describe the bug**
Paperless-AI re-opens the setup page after server restarts, even though it was set up before. 
It asks for a new user and password, all other settings were stored and are shown correctly.
Upon entering a new user name, the user is created (according to logs) but the new user can't log in.
Instead, the old credentials keep working.
Also, if the new user is the same name as the old user and only a new password is entered, the old password remains valid (new password is not saved). 

**To Reproduce**
1. use an instance with completed setup (or create one accordingly)
2. docker compose down
3. docker compose up 
(leads to recreation of the container)
4. go to webui, e.g. http://paperless-ai.local/dashboard

**Expected behavior**
The login screen or target url is expected to show

**Screenshots**

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/21d31fab-2ed2-403a-80dd-ba7e52a5a7d4" />

**Desktop (please complete the following information):**
 - OS: Unraid 7
 - Firefox 134

**Additional context**
My compose-config:
```
[...]
  ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/paperless/ai:/app/data
    ports:
      - "8911:3000"
    restart: unless-stopped
    depends_on: 
      - webserver
```

I'll be happy to provide further information and hope I could help to improve the app =)
