### ISSUE TITLE
PUID/PGID Support

### ISSUE THREAD

**Issue by truthsword** [clusterzx/paperless-ai#253]
**Is your feature request related to a problem? Please describe.**
Objective to drop/reduce root priviledges.

**Describe the solution you'd like**

compose.yaml
```
services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID: 1000
      - PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - paperless-ai_data:/app/data

volumes:
  paperless-ai_data:
```

**Comment by clusterzx** [comment]
Added your config. Thank you for the good issue.

**Comment by GyroGearl00se** [comment]
services.paperless-ai.environment.[0]: unexpected type map[string]interface {}

environment should look like:


environment:
      - PUID=1000
      - PGID=1000

**Comment by truthsword** [comment]
Remove the space after the colon (fixed above)
```
services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID:1000
      - PGID:1000
    ports:
      - 3000:3000
    volumes:
      - paperless-ai_data:/app/data

volumes:
```
