### ISSUE TITLE
SqliteError: unable to open database file

### ISSUE THREAD

**Issue by doing5** [clusterzx/paperless-ai#290]
Hi together,

Following the howto using docker compose I get the following error:
paperless-ai             | SqliteError: unable to open database file
paperless-ai             |     at new Database (/app/node_modules/better-sqlite3/lib/database.js:69:26)
paperless-ai             |     at Object.<anonymous> (/app/models/document.js:14:12)
paperless-ai             |     at Module._compile (node:internal/modules/cjs/loader:1723:14)
paperless-ai             |     at Object..js (node:internal/modules/cjs/loader:1888:10)
paperless-ai             |     at Module.load (node:internal/modules/cjs/loader:1458:32)
paperless-ai             |     at Function._load (node:internal/modules/cjs/loader:1275:12)
paperless-ai             |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
paperless-ai             |     at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
paperless-ai             |     at Module.<anonymous> (node:internal/modules/cjs/loader:1480:12)
paperless-ai             |     at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
paperless-ai             | 2025-02-06T18:47:25: PM2 log: App name:paperless-ai id:0 disconnected
paperless-ai             | 2025-02-06T18:47:25: PM2 log: App [paperless-ai:0] exited with code [0] via signal [SIGINT]
paperless-ai             | 2025-02-06T18:47:25: PM2 log: App [paperless-ai:0] will restart in 100ms
paperless-ai             | 2025-02-06T18:47:26: PM2 log: App [paperless-ai:0] starting in -cluster mode-
paperless-ai             | 2025-02-06T18:47:26: PM2 log: App [paperless-ai:0] online

with the following docker-compose.yml:
(changes gotenberg endpoint to 3001 to not interfere with paperless-ai port 3000)
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /home/lukas/paperless-ngx/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /home/lukas/paperless-ngx/data:/usr/src/paperless/data
      - /home/lukas/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/lukas/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3001
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  paperless-mailservice:
    image: carlosz1986/paperless-mailservice:2.3
    volumes:
      - ./paperless-mailservice:/app
      - ./paperless-mailservice/config:/config
    depends_on:
      - webserver
    restart: unless-stopped

  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    network_mode: bridge
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    volumes:
      - /home/lukas/paperless-ngx/paperless-ai_data:/app/data
    ports:
      - 3000:3000

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
  paperless-ai_data:

 - OS: [Debian 12.9 CT in Proxmox]
 - Browser [Firefox]

![Image](https://github.com/user-attachments/assets/2b97c14f-dfaa-4a4a-8e7c-85ef4ccc288f)

![Image](https://github.com/user-attachments/assets/b3c368a7-1d43-4a74-bf89-dff5d1fa350c)

**Comment by Wastus** [comment]
I'm seeing the same issue, currently trying to figure out what it's trying to achieve - which SQlite database is missing.

**Comment by clusterzx** [comment]
@doing5 @Wastus 

What is your install process?
Can you walk me through front start to error.

**Comment by doing5** [comment]
It was an issue because of the wrong user permission.

**Comment by Wastus** [comment]
@clusterzx 
I'm running on OpenMediaVault 7.6.0-1 which is based on Debian Bookworm.

I'm using docker compose v2.32.4 and I adapted the docker-compose.yml from the current main. I'm not entirely sure why, but I never got the env file to work with the OpenMediaVault Compose Plugin (web based interface to docker compose), so I put the stuff in the yml.

This also seems to be related to user permissions. My user is 1000:100 and the folder I mount as volume has all the rights for that user.

```yaml
services:
  paperless-ai:
    image: clusterzx/paperless-ai
    user: "1000:100"
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "PAPERLESS_AI_INITIAL_SETUP=yes"
      - "PAPERLESS_API_URL=http://localhost:8010"
      - "PAPERLESS_API_TOKEN=<xyz>"
      - "PAPERLESS_USERNAME=<xyz>"
      - "AI_PROVIDER=ollama"
      - "OPENAI_API_KEY="
      - "OPENAI_MODEL="
      - "OLLAMA_API_URL=http://localhost:11434"
      - "OLLAMA_MODEL=phi4"
      - "SCAN_INTERVAL=*/30 * * * *"
      - "SYSTEM_PROMPT=<Default Prompt>"
      - "PROCESS_PREDEFINED_DOCUMENTS=yes"
      - "TAGS=pre-process"
      - "ADD_AI_PROCESSED_TAG=no"
      - "AI_PROCESSED_TAG_NAME=ai-processed"
      - "USE_PROMPT_TAGS=no"
      - "PROMPT_TAGS="
      - "USE_EXISTING_DATA=no"
      - "API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - "CUSTOM_API_KEY=xxxxxxxxxxxxxxxxxxxxxxx"
      - "CUSTOM_BASE_URL=https://api.deepseek.com/v1"
      - "CUSTOM_MODEL=deepseek-chat"
    ports:
      - 3000:3000
    volumes:
      - "/srv/mergerfs/datavault/datavault/Paperless/aidata:/app/data"
```

I have added `user: "1000:100"` which now got rid of the SqliteError, but now the next issue arises with:
```
paperless-ai  |     Error: EACCES: permission denied, mkdir 'logs'
paperless-ai  |     at Object.mkdirSync (node:fs:1364:26)
paperless-ai  |     at new Logger (/app/services/loggerService.js:14:16)
paperless-ai  |     at Object.<anonymous> (/app/server.js:16:20)
paperless-ai  |     at Module._compile (node:internal/modules/cjs/loader:1562:14)
paperless-ai  |     at Object..js (node:internal/modules/cjs/loader:1699:10)
paperless-ai  |     at Module.load (node:internal/modules/cjs/loader:1313:32)
paperless-ai  |     at Function._load (node:internal/modules/cjs/loader:1123:12)
paperless-ai  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
paperless-ai  |     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
paperless-ai  |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
```

Not sure where the logs folder is getting created.

**Comment by clusterzx** [comment]
> [@clusterzx](https://github.com/clusterzx) I'm running on OpenMediaVault 7.6.0-1 which is based on Debian Bookworm.
> 
> I'm using docker compose v2.32.4 and I adapted the docker-compose.yml from the current main. I'm not entirely sure why, but I never got the env file to work with the OpenMediaVault Compose Plugin (web based interface to docker compose), so I put the stuff in the yml.
> 
> This also seems to be related to user permissions. My user is 1000:100 and the folder I mount as volume has all the rights for that user.
> 
> services:
>   paperless-ai:
>     image: clusterzx/paperless-ai
>     user: "1000:100"
>     container_name: paperless-ai
>     restart: unless-stopped
>     cap_drop:
>       - ALL
>     security_opt:
>       - no-new-privileges=true
>     environment:
>       - "PUID=1000"
>       - "PGID=100"
>       - "PAPERLESS_AI_INITIAL_SETUP=yes"
>       - "PAPERLESS_API_URL=http://localhost:8010"
>       - "PAPERLESS_API_TOKEN=<xyz>"
>       - "PAPERLESS_USERNAME=<xyz>"
>       - "AI_PROVIDER=ollama"
>       - "OPENAI_API_KEY="
>       - "OPENAI_MODEL="
>       - "OLLAMA_API_URL=http://localhost:11434"
>       - "OLLAMA_MODEL=phi4"
>       - "SCAN_INTERVAL=*/30 * * * *"
>       - "SYSTEM_PROMPT=<Default Prompt>"
>       - "PROCESS_PREDEFINED_DOCUMENTS=yes"
>       - "TAGS=pre-process"
>       - "ADD_AI_PROCESSED_TAG=no"
>       - "AI_PROCESSED_TAG_NAME=ai-processed"
>       - "USE_PROMPT_TAGS=no"
>       - "PROMPT_TAGS="
>       - "USE_EXISTING_DATA=no"
>       - "API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>       - "CUSTOM_API_KEY=xxxxxxxxxxxxxxxxxxxxxxx"
>       - "CUSTOM_BASE_URL=https://api.deepseek.com/v1"
>       - "CUSTOM_MODEL=deepseek-chat"
>     ports:
>       - 3000:3000
>     volumes:
>       - "/srv/mergerfs/datavault/datavault/Paperless/aidata:/app/data"
> I have added `user: "1000:100"` which now got rid of the SqliteError, but now the next issue arises with:
> 
> ```
> paperless-ai  |     Error: EACCES: permission denied, mkdir 'logs'
> paperless-ai  |     at Object.mkdirSync (node:fs:1364:26)
> paperless-ai  |     at new Logger (/app/services/loggerService.js:14:16)
> paperless-ai  |     at Object.<anonymous> (/app/server.js:16:20)
> paperless-ai  |     at Module._compile (node:internal/modules/cjs/loader:1562:14)
> paperless-ai  |     at Object..js (node:internal/modules/cjs/loader:1699:10)
> paperless-ai  |     at Module.load (node:internal/modules/cjs/loader:1313:32)
> paperless-ai  |     at Function._load (node:internal/modules/cjs/loader:1123:12)
> paperless-ai  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
> paperless-ai  |     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
> paperless-ai  |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
> ```
> 
> Not sure where the logs folder is getting created.

First of all you do not configure the app through environment variables, this is only done with the setup process.
Second you should use the standard docker-compose file (you have errors in there for example PGID=100[0] )

**Comment by Wastus** [comment]
Well, I tried with PGID = 1000 at first, but that didn't make a difference. What makes a difference is removing all the environment variables.
The presence of an .env.example in the repository led me on a stray path I guess. And that the environment variables break stuff - might need some removing of code evaluating those if they're not supposed to make a difference.

Thanks for the hint, though, let's see how it works for real now.

**Comment by clusterzx** [comment]
The .env.example is a remnant of old times and was only used for developing reasons. I will remove it in the next days.
Have fun and good luck with Paperless-AI

**Comment by o10s** [comment]
@clusterzx I have the same issue, using the given compose file (adapted to run on my own folder, in a custom network and with traefik):
```
paperless-ai:
    image: clusterzx/paperless-ai:2.7.1
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=1000
      - PGID=1000
      - PAPERLESS_AI_PORT=3000
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperlessai.rule=Host(`paperlessai.${DOMAIN}`)"
      - "traefik.http.routers.paperlessai.entrypoints=websecure"
      - "traefik.http.routers.paperlessai.tls=true"
      - 'traefik.http.routers.paperlessai.tls.certresolver=${CERT_RESOLVER}resolver'
      - 'traefik.http.routers.paperlessai.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.paperlessai.tls.domains[0].sans=*.${DOMAIN}'
    volumes:
      - /${STORAGE_PATH}/paperless-ai/data:/app/data
```

The folder /${STORAGE_PATH}/paperless-ai/data is chown to 1000:1000 recursively as well as chmod 755.
As user 1000:1000 I can create files and folders however the container can't create directories (but files are ok)
I end up with the following files in my storage path:
```
-rwxr-xr-x 1 1000 1000  4096 Mar  5 11:29 documents.db
-rwxr-xr-x 1 1000 1000 32768 Mar  5 11:39 documents.db-shm
-rwxr-xr-x 1 1000 1000 57712 Mar  5 11:29 documents.db-wal
```
