### ISSUE TITLE
[Bug]: Error Failed to initialize connection to Paperless-ngx. Please check URL and Token.

### ISSUE THREAD

**Issue by pikiton** [clusterzx/paperless-ai#336]
### 🔍 Bug Summary

I get an error when I save configuration. Windows 11, docker on localhost:3000 and could not connect to paperai-ngx on localhost:8000

### 📖 Description

![Image](https://github.com/user-attachments/assets/c6af5cec-9c1d-41ce-a4dd-cf76cf3600c5)

2025-02-14 13:57:23 [ERROR] Failed to initialize with credentials: connect ECONNREFUSED 127.0.0.1:8000

### 🔄 Steps to Reproduce

http://localhost:3000/setup

get an error Error

Failed to initialize connection to Paperless-ngx. Please check URL and Token.

### ✅ Expected Behavior

connect to server

### ❌ Actual Behavior

not connect to server

### 📜 Docker Logs

```shell
025-02-14 13:57:23     '- Short and concise, NO ADDRESSES\n' +
2025-02-14 13:57:23     '- Contains the most important identification features\n' +
2025-02-14 13:57:23     '- For invoices/orders, mention invoice/order number if available\n' +
2025-02-14 13:57:23     '- The output language is the one used in the document! IMPORTANT!\n' +
2025-02-14 13:57:23     '\n' +
2025-02-14 13:57:23     'For the correspondent:\n' +
2025-02-14 13:57:23     '- Identify the sender or institution\n' +
2025-02-14 13:57:23     '- When generating the correspondent, always create the shortest possible form of the company name (e.g. "Amazon" instead of "Amazon EU SARL, German branch")\n' +
2025-02-14 13:57:23     '\n' +
2025-02-14 13:57:23     'For the document date:\n' +
2025-02-14 13:57:23     '- Extract the date of the document\n' +
2025-02-14 13:57:23     '- Use the format YYYY-MM-DD\n' +
2025-02-14 13:57:23     '- If multiple dates are present, use the most relevant one\n' +
2025-02-14 13:57:23     '\n' +
2025-02-14 13:57:23     'For the language:\n' +
2025-02-14 13:57:23     '- Determine the document language\n' +
2025-02-14 13:57:23     '- Use language codes like "de" for German or "en" for English\n' +
2025-02-14 13:57:23     '- If the language is not clear, use "und" as a placeholder'
2025-02-14 13:57:23 }
2025-02-14 13:57:23 [ERROR] Failed to initialize with credentials: connect ECONNREFUSED 127.0.0.1:8000
```

### 📜 Paperless-ngx Logs

```shell

```

### 🖥️ Desktop Environment

Windows

### 💻 OS Version

windows 11 ubuntu-24.04 wsl

### 🌐 Browser

Chrome

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [x] I have tried debugging this issue on my own
- [x] I can provide a fix and submit a PR

**Comment by clusterzx** [comment]
Thanks for this rediculous issue post here!

1. Do you even try to fix your own fault? Look here:
![Image](https://github.com/user-attachments/assets/e2a7357d-94cf-43d4-96ae-b43d7a9699d0)

2. The "Additional Information" part here was clearly abused! So you say EVERYONE has this problem? So no one could have ever used that tool before - I wonder where all the issues are, how so many stars are gained? Also you say you tried debugging yourself... what did you do? I guess nothing! Also you want to present a fix? Please show me the fix to the problem that is not. 

I've got much patience but you clearly overstep that!

**Comment by theCrius** [comment]
[Spongebob meme: one year later]

Hey, I am a different guy with the same problem 😆 

It might be the late hours here but I seem to have run into the same issue as this guy except I am running this on an home server in docker, via docker compose.

<img width="926" height="884" alt="Image" src="https://github.com/user-attachments/assets/dd0b1bb5-db6c-473a-80c1-663ad7f71346" />

<img width="858" height="552" alt="Image" src="https://github.com/user-attachments/assets/c9ed7d7d-24e1-4a25-8a8c-e1c79bb69286" />

The docker container log only show this as error:

` STDERR [ERROR] Failed to initialize with credentials: Request failed with status code 400`

This is my paperless-ngx configuration. It works, no issue with it, it's running since 6-7 months now.

```
  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    networks:
      - ethernet_network
      - proxy
    # ports:
    #   - "8000:8000"  # Proxied via NPM
    volumes:
      - ${DATA_DIR:-$HOME}/paperless/data:/usr/src/paperless/data
      - ${DATA_DIR:-$HOME}/paperless/media:/usr/src/paperless/media
      - ${DATA_DIR:-$HOME}/paperless/export:/usr/src/paperless/export
      - ${DATA_DIR:-$HOME}/paperless/consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://redis-paperless:6379
      - PAPERLESS_DBHOST=paperless-db
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=${PAPERLESS_DB_PASSWORD}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_TIME_ZONE=${TZ}
      - PAPERLESS_OCR_LANGUAGE=eng+ita
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_URL=${PAPERLESS_URL}
      - PAPERLESS_ALLOWED_HOSTS=${PAPERLESS_ALLOWED_HOSTS}
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=${PAPERLESS_CSRF_TRUSTED_ORIGINS}
      - USERMAP_UID=${PUID}
      - USERMAP_GID=${PGID}
      # Consumer settings
      - PAPERLESS_CONSUMER_POLLING=0
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
      - PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
    depends_on:
      paperless-db:
        condition: service_healthy
      redis-paperless:
        condition: service_healthy
    restart: unless-stopped
```

And this is paperless-ai:

```
  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    networks:
      - ethernet_network
      - proxy
    # ports:
    #   - "3000:3000"       # Proxied via NPM
    volumes:
      - ${DATA_DIR}/paperless-ai:/app/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      # Paperless-ngx connection
      - PAPERLESS_API_URL=http://paperless-webserver:8000
      - PAPERLESS_API_TOKEN=${PAPERLESS_AI_TOKEN}
      # Ollama LLM configuration
      - AI_PROVIDER=ollama
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=${PAPERLESS_AI_MODEL}
      # Processing settings
      - SCAN_INTERVAL=${PAPERLESS_AI_SCAN_INTERVAL}
      - ADD_AI_TAG=true
      - PROCESS_PREDEFINED_DOCUMENTS=no
      - AI_TAG_NAME=AI
    depends_on:
      - paperless-webserver
    restart: unless-stopped
```

I double checked the token and the username, copy pasting the values and regenerating the token multiple times as well.

Here is an example request and response:

```
{"username":"crius","password":"ihJGbt%Vj0N8pYAd","confirmPassword":"ihJGbt%Vj0N8pYAd","paperlessUrl":"http://paperless-webserver:8000","paperlessToken":"df61dd5fc348c3c43c77ef6ba055114f346caadf","paperlessUsername":"ai-automation","aiProvider":"ollama","openaiKey":"","openaiModel":"gpt-4o-mini","ollamaUrl":"http://ollama:11434","ollamaModel":"qwen2.5:7b","customBaseUrl":"","customApiKey":"","customModel":"","azureEndpoint":"","azureApiKey":"","azureDeploymentName":"","azureApiVersion":"","tokenLimit":"128000","responseTokens":"1000","useExistingData":"yes","scanInterval":"*/30 * * * *","showTags":"no","tags":"","aiProcessedTag":"yes","aiTagName":"AI","usePromptTags":"no","promptTags":"","activateTagging":"on","activateCorrespondents":"on","activateDocumentType":"on","activateTitle":"on","customFields":"{\"custom_fields\":[]}","systemPrompt":"If you are unsure on a document, do not make changes to existing metadata, simply add new ones."}
```

Everything seems fine to me, still, it gets a 400 response:

```
{"error":"Failed to initialize connection to Paperless-ngx. Please check URL and Token."}
```

As "proof" that the user and token are correct:

<img width="1423" height="754" alt="Image" src="https://github.com/user-attachments/assets/529994bc-52c3-450d-92d3-3cae478a3a58" />

<img width="260" height="79" alt="Image" src="https://github.com/user-attachments/assets/1fca53e1-28d2-41d2-9a1d-75a47b55eff0" />

I don't care for the exposed sensitive data, it's all locked in local and I'll change password/token as soon as I submit this comment.

---

Could it be some symbol in password or token making it fail and the message being a simple standard fallback message that is misleading? Am I simply missing something stupid in my configuration as per tradition when you do something at 1AM? 😆 

If it seems all correct to you too, If you can point me at where in the codebase this logic happens, I can give it a look.

Thanks a lot for all the workon this project anyway <3
