### ISSUE TITLE
[Bug]: Cannot Update Settings

### ISSUE THREAD

**Issue by Mx772** [clusterzx/paperless-ai#355]
### 🔍 Bug Summary

When updating Settings, get 'formData.get(...) is null' error

### 📖 Description

Attempting to update the configuration via the 'settings' page results in ERROR formData.get(...) is null.

![Image](https://github.com/user-attachments/assets/64fc0891-1e6b-4e7b-bf03-4f5f1c70c9a6)

Checking logs, no logs.
Checking network calls via Browser's network call also shows no network calls?

Compose:
```
services:
  paperless-ai:
      container_name: paperless-ai
      volumes:
          - ./paperless-ai_data:/app/data
      ports:
          - 5116:3000
      restart: unless-stopped
      image: clusterzx/paperless-ai

volumes:
  paperless-ai_data:
```
Not sure if there is some file missing from the dir maybe?
```
-rw-r--r-- 1 root root 36864 Feb 17 16:28 documents.db
-rw-r--r-- 1 root root 32768 Feb 17 16:29 documents.db-shm
-rw-r--r-- 1 root root     0 Feb 17 16:29 documents.db-wal
-rw-r--r-- 1 root root   952 Feb 17 16:29 .env
```

Note: The server is linux (ubuntu 22)

### 🔄 Steps to Reproduce

1. Go through initial setup
2. Go to settings page
3. Make change (I toggled title generation)
4. Click 'Save' at bottom
5. Error

### ✅ Expected Behavior

Save Configuration

### ❌ Actual Behavior

Error - No saving

### 📜 Docker Logs

```shell
None...
```

### 📜 Paperless-ngx Logs

```shell
n/a
```

### 🖥️ Desktop Environment

Windows

### 💻 OS Version

Windows 11

### 🌐 Browser

None

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [x] I have tried debugging this issue on my own
- [ ] I can provide a fix and submit a PR

### 📌 Extra Notes

> I am sure that this problem is affecting everyone, not only me*

Not sure how you want me to test this? I'm assuming it's not affecting everyone, but I've destroyed the container, repulled, etc, No dice.
