### ISSUE TITLE
[Bug]: Docker Compose environment variables not being used/overwritten

### ISSUE THREAD

**Issue by leon3011** [clusterzx/paperless-ai#358]
### 🔍 Bug Summary

I set up Paperless-AI with environment variables in my Docker Compose file, but some of them are not being used or are being ignored.

### 📖 Description

For example, I set `PAPERLESS_AI_INITIAL_SETUP: no`, but I still have to go through the initial setup. Some other environment variables, like `PAPERLESS_API_URL` and `SYSTEM_PROMPT`, are prefilled in the setup forms, but the custom LLM values are not.  

Additionally, I noticed that the environment variables defined in the Docker Compose file take precedence over values set during the setup process. For example, I had a paperless-ngx token in my Compose environment variables but later changed the token. When I provided the new token in the setup, Paperless-AI still used the old one from the Compose environment. The same issue applies to the custom LLM model.

### 🔄 Steps to Reproduce

1. Run the following `docker-compose.yml` file:  

   ```yaml
   paperless-ai:
       image: clusterzx/paperless-ai
       environment:
         PAPERLESS_AI_INITIAL_SETUP: no
         PAPERLESS_API_URL: http://<url>:8000/api
         PAPERLESS_API_TOKEN: <ngx token>
         PAPERLESS_USERNAME: <ngx username>
         AI_PROVIDER: custom
         SCAN_INTERVAL: '*/30 * * * *'
         SYSTEM_PROMPT: <prompt>
         ADD_AI_PROCESSED_TAG: no
         USE_PROMPT_TAGS: no
         USE_EXISTING_DATA: no
         CUSTOM_API_KEY: <token>
         CUSTOM_BASE_URL: https://openrouter.ai/api/v1
         CUSTOM_MODEL: google/gemini-2.0-flash-exp:free
       ports:
         - 3000:3000
       volumes:
         - ./paperless-ai:/app/data
   ```  

2. Open `localhost:3000`.  
3. You are still required to enter most values manually, though some are prefilled.

### ✅ Expected Behavior

I would expect the initial setup to be skipped entirely since all the required values are already provided in the environment variables. However, instead of skipping, the setup process still prompts for most of the values manually, even though some are prefilled.

### ❌ Actual Behavior

On opening the app, I am redirected to `/setup` instead of the dashboard, even though all required environment variables are set.

### 📜 Docker Logs

```shell

```

### 📜 Paperless-ngx Logs

```shell

```

### 🖥️ Desktop Environment

Linux

### 🌐 Browser

Chrome

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [ ] I have tried debugging this issue on my own
- [ ] I can provide a fix and submit a PR
