### ISSUE TITLE
[Bug]: Startup fails if paperless-ngx is unreachable

### ISSUE THREAD

**Issue by saladpanda** [clusterzx/paperless-ai#367]
### 🔍 Bug Summary

Startup of paperless-ai fails in a weird way if paperless-ngx is unreachable during startup.

### 📖 Description

When starting paperless-ngx and paperless-ai from the same docker-compose.yml paperless-ai usually fails to start correctly. After login it will always redirect to the settings page saying that the settings are broken.
Looking at the logs explains what happened:

```
paperless-ai  | Validating Paperless config for: http://paperless-ngx:8000/api/documents/
paperless-ai  | Paperless validation error: connect ECONNREFUSED 172.18.0.3:8000
paperless-ai  | Configuration validation failed: Invalid Paperless configuration
paperless-ai  | Setup not completed. Visit http://your-ip-or-host.com:3000/setup to complete setup.
```

paperless-ai was unable to reach paperless-ngx (because it was not fully started yet) and therefore could not validate whether the instance and the API key worked.

I solved this by defining a dependency with condition `service_healthy` in my docker-compose.yml, but would consider this a workaround. It would be more elegant if paperless-ai handled this case more gracefully with rechecks and clear user-facing error/warning messages.

My docker-compose.yml (see `healthcheck` and `depends_on`):

```yaml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./paperless-data:/usr/src/paperless/data
      - ./paperless-media:/usr/src/paperless/media
      - ./paperless-export:/usr/src/paperless/export
      - ./paperless-consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    healthcheck:
      test: curl -fsS --max-time 2 http://localhost:8000/accounts/login/ | grep -iq paperless-ngx || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - ./paperless-ai_data:/app/data
      - ./paperless-ai_logs:/app/logs
    depends_on:
      paperless-ngx:
        condition: service_healthy

```

### 🔄 Steps to Reproduce

1. Write a docker-compose.yml with paperless-ngx and paperless-ai in it.
2. `docker compose up`

### ✅ Expected Behavior

paperless-ai should perform a few retries before giving up on paperless-ngx and then communicate the exact failure condition to the user in a clear way.

### ❌ Actual Behavior

paperless-ai only outputs an error hinting at the problem to the logs (not visible to the average user) and forwards to the settings page which says the setings are broken (I don't remember the exact wording).

### 📜 Docker Logs

```shell
paperless-ai  | Validating Paperless config for: http://paperless-ngx:8000/api/documents/
paperless-ai  | Paperless validation error: connect ECONNREFUSED 172.18.0.3:8000
paperless-ai  | Configuration validation failed: Invalid Paperless configuration
paperless-ai  | Setup not completed. Visit http://your-ip-or-host.com:3000/setup to complete setup.
```

### 📜 Paperless-ngx Logs

```shell

```

### 🖥️ Desktop Environment

Linux

### 🌐 Browser

None

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [x] I have tried debugging this issue on my own
- [ ] I can provide a fix and submit a PR
