### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by rpakishore** [clusterzx/paperless-ai#491]
### 🔍 Bug Summary

Failed to initialize with credentials Error When Connecting to Paperless-ngx

### 📖 Description

Unable to connect the paperless-ai to paperless-ngx server. 

On saving the configuration ends up with the following error in logs

> [ERROR] Failed to initialize with credentials: connect ETIMEDOUT 192.168.X.X:18000

### 🔄 Steps to Reproduce

Have an existing paperless-ngx server running locally at 192.168.X.X:18000. 

I have a valid API Token (verified using the api interface of paperless-ngx)

<img width="849" alt="Image" src="https://github.com/user-attachments/assets/f76eefb5-36f7-4a07-8471-52081edd99ea" />

Steps taken 
1. Installed paperless-ai using the following docker-compose.yml
```yaml
dataraft_paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: dataraft_paperless-ai
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - paperless-ai:/app/data
```

2. Visited `http://192.168.X.X:3000/setup` to setup
3. Filled out all 4 sections `User Setup`, `Connection`, `AI Settings`, `Advanced`

![Image](https://github.com/user-attachments/assets/be3183dd-04cc-4153-9c6b-ae46e0688ff5)

![Image](https://github.com/user-attachments/assets/57c20ea3-8699-44a9-8750-0137f18e15ad)

4. Clicked `Save Configuration`

### ✅ Expected Behavior

Show the configuration saved and move on to dashboard

### ❌ Actual Behavior

![Image](https://github.com/user-attachments/assets/af7b3961-99d9-4bfb-830f-6835b2af313e)

### 📜 Docker Logs

```shell
Setup request received: {
  username: 'XXXXXXX',
  password: '******',
  confirmPassword: '******',
  paperlessUrl: 'http://192.168.XX.XX:18000',
  paperlessToken: '******',
  paperlessUsername: 'XXXXXXXX',
  aiProvider: 'ollama',
  openaiKey: '******',
  openaiModel: 'gpt-4o-mini',
  ollamaUrl: 'http://192.168.XX.YY:11434',
  ollamaModel: 'general_large',
  customBaseUrl: '',
  customApiKey: '******',
  customModel: '',
  azureEndpoint: '',
  azureApiKey: '',
  azureDeploymentName: '',
  azureApiVersion: '',
  useExistingData: 'no',
  scanInterval: '*/30 * * * *',
  showTags: 'no',
  tags: '',
  aiProcessedTag: 'yes',
  aiTagName: 'ai-processed',
  usePromptTags: 'no',
  promptTags: 'Receipt',
  activateTagging: 'on',
  activateCorrespondents: 'on',
  activateDocumentType: 'on',
  activateTitle: 'on',
  customFields: '{"custom_fields":[]}',
  systemPrompt: 'You are a personalized document analyzer. Your task is to analyze documents and extract relevant information.\n' +
    '\n' +
    'Analyze the document content and extract the following information into a structured JSON object:\n' +
    '\n' +
    '1. title: Create a concise, meaningful title for the document\n' +
    '2. correspondent: Identify the sender/institution but do not include addresses\n' +
    '3. tags: Select up to 4 relevant thematic tags\n' +
    '4. document_date: Extract the document date (format: YYYY-MM-DD)\n' +
    '5. document_type: Determine a precise type that classifies the document (e.g. Invoice, Contract, Employer, Information and so on)\n' +
    '6. language: Determine the document language (e.g. "de" or "en")\n' +
    '      \n' +
    'Important rules for the analysis:\n' +
    '\n' +
    'For tags:\n' +
    '- FIRST check the existing tags before suggesting new ones\n' +
    '- Use only relevant categories\n' +
    '- Maximum 4 tags per document, less if sufficient (at least 1)\n' +
    '- Avoid generic or too specific tags\n' +
    '- Use only the most important information for tag creation\n' +
    '- The output language is the one used in the document! IMPORTANT!\n' +
    '\n' +
    'For the title:\n' +
    '- Short and concise, NO ADDRESSES\n' +
    '- Contains the most important identification features\n' +
    '- For invoices/orders, mention invoice/order number if available\n' +
    '- The output language is the one used in the document! IMPORTANT!\n' +
    '\n' +
    'For the correspondent:\n' +
    '- Identify the sender or institution\n' +
    '- When generating the correspondent, always create the shortest possible form of the company name (e.g. "Amazon" instead of "Amazon EU SARL, German branch")\n' +
    '\n' +
    'For the document date:\n' +
    '- Extract the date of the document\n' +
    '- Use the format YYYY-MM-DD\n' +
    '- If multiple dates are present, use the most relevant one\n' +
    '\n' +
    'For the language:\n' +
    '- Determine the document language\n' +
    '- Use language codes like "de" for German or "en" for English\n' +
    '- If the language is not clear, use "und" as a placeholder'
}
[ERROR] Failed to initialize with credentials: connect ETIMEDOUT 192.168.XX.XX:18000
```

### 📜 Paperless-ngx Logs

```shell
No new logs generated
```

### 🖼️ Screenshots of your settings page

-

### 🖥️ Desktop Environment

Linux

### 💻 OS Version

Ubuntu 22.04.5 LTS

### 🌐 Browser

Firefox

### 🔢 Browser Version

138.0b9

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [x] I have tried debugging this issue on my own
- [ ] I can provide a fix and submit a PR

**Comment by SilentJMA** [comment]
Have you tried adding at the end of the link '/v1'?

**Comment by rpakishore** [comment]
Hey @SilentJMA, Do you mean the ollama url or the paperless-url? 

I have tried the following and still getting the same error:
1. Set paperless url to http://192.168.XX.XX:18000/v1 and change to openai model with valid key
2. Set paperless url to http://192.168.XX.XX:18000 and change to openai model with a valid key

The issue seems to be for `paperless-ai` to communicate with the `paperless-ngx` webserver endpoint. 

Following is my paperless-ngx + paperless-ai deployment if it helps

```yaml

networks:
  paperless:
    name: paperless
    external: false

services:
  paperless_db:
    image: docker.io/library/redis:7
    container_name: paperless_db
    restart: unless-stopped
    volumes:
      - paperless_redisdata:/data
    networks:
      - paperless

  paperless_webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_gotenberg
      - paperless_tika
    ports:
      - "18000:8000"
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless_db:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless_gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless_tika:9998
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_URL: https://paperless.ubuntu-server.ak
      PAPERLESS_TIME_ZONE: America/Vancouver
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_CONSUMER_POLLING: 3600
    networks:
      - paperless

  paperless_gotenberg:
    container_name: paperless_gotenberg
    image: docker.io/gotenberg/gotenberg:8.19
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  paperless_tika:
    container_name: paperless_tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - paperless

  paperless-ai:
    image: clusterzx/paperless-ai:latest
    container_name: paperless-ai
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - paperless-ai:/app/data
```
