### ISSUE TITLE
Allow for stateless confirgation via ENV Var

### ISSUE THREAD

**Issue by gavinmcfall** [clusterzx/paperless-ai#520]
**Is your feature request related to a problem? Please describe.**
At the moment Paperless-AI requires the user to go through a wizard on launch to setup the app and then writes to /app/data/.env all the vars that get set in that process.  This means if you lsoe your PVC, you lose you config and have to start again.

**Describe the solution you'd like**
Allow for all those vars to be set as ENV vars and get read from ENV or the /app/data/.env gets populated from the ENV Vars

**Describe alternatives you've considered**
Ive considered using an init container to do this, but its really messy

```yaml
        initContainers:
          generate-env:
            image: alpine/git
            command: ["/bin/sh", "-c"]
            args:
              - |
                mkdir -p /app/data;
                env | grep -E '^(list things to grep here)' \
                sed 's/^/export /' > /app/data/.env
                echo "Generated /app/data/.env:";
                cat /app/data/.env;
                chmod 644 /app/data/.env; # Ensure proper permissions

            volumeMounts:
              - name: config # Mount the same persistent volume for /app/data
                mountPath: /app/data
```

**Additional context**
Many of us take an Infrastructure as code approach a prefer not to reply on configs and wizards to set things up.
Paperless-ngx which this connects with, does this.
