### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by bandundu** [clusterzx/paperless-ai#543]
### 🔍 Bug Summary

Bug Report: Missing `punkt_tab` Resource in NLTK on Docker Image

### 📖 Description

**Issue Summary**  
When running `clusterzx/paperless-ai` using the latest Docker image via `docker-compose`, the container fails to do RAG chat due to a missing NLTK resource: `punkt_tab`.

### 🔄 Steps to Reproduce

1. Clone the repo
2. Deploy using provided `docker-compose.yml`
3. Check logs after container startup

**docker-compose.yml Snippet**
```yaml
services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    network_mode: bridge
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      - PUID=1000
      - PGID=1000
      - PAPERLESS_AI_PORT=${PAPERLESS_AI_PORT:-3000}
      - RAG_SERVICE_URL=http://localhost:8000
      - RAG_SERVICE_ENABLED=true
    ports:
      - "8343:${PAPERLESS_AI_PORT:-3000}"
    volumes:
      - paperless-ai_data:/app/data

volumes:
  paperless-ai_data:
```

### ✅ Expected Behavior

NO Error

### ❌ Actual Behavior

**Logs**

>  Resource punkt_tab not found.
>  Please use the NLTK Downloader to obtain the resource:
> import nltk
> nltk.download('punkt_tab')
> 
> Attempted to load tokenizers/punkt_tab/English/
> Searched in:
> 	•	‘/root/nltk_data’
> 	•	‘/app/venv/nltk_data’
> 	•	‘/app/venv/share/nltk_data’
> 	•	‘/app/venv/lib/nltk_data’
> 	•	‘/usr/share/nltk_data’
> 	•	‘/usr/local/share/nltk_data’
> 	•	‘/usr/lib/nltk_data’
> 	•	‘/usr/local/lib/nltk_data’

### 📜 Docker Logs

```shell

```

### 📜 Paperless-ngx Logs

```shell

```

### 🖥️ Desktop Environment

Linux

### 🌐 Browser

None

### 📝 Additional Information

- [x] I have checked existing issues and this is not a duplicate
- [x] I am sure that this problem is affecting everyone, not only me
- [ ] I have tried debugging this issue on my own
- [ ] I can provide a fix and submit a PR
